default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 172.17.64.1
  username: postgres
  password: root

development:
  <<: *default
  database: Biblioteca_de_Proiect

test:
  <<: *default
  database: biblioteca_test

production:
  <<: *default
  database: biblioteca_production